# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [35]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor,random_tensor.shape

(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071],
         [0.6297, 0.3653, 0.8513, 0.8549, 0.5509, 0.2868, 0.2063],
         [0.4451, 0.3593, 0.7204, 0.0731, 0.9699, 0.1078, 0.8829],
         [0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
         [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691, 0.7437],
         [0.9592, 0.3887, 0.2214, 0.3742, 0.1953, 0.7405, 0.2529],
         [0.2332, 0.9314, 0.9575, 0.5575, 0.4134, 0.4355, 0.7369]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
random_tensor_B = torch.rand(size=(1, 7))
print(f"Random Tensor B: {random_tensor_B}")

# Perform matrix multiplication 
print(f"\nMultiplying: {random_tensor.shape} @ {random_tensor_B.T.shape}")
output = torch.matmul(random_tensor, random_tensor_B.T)
print(f"\nOutput: {output}")
print(f"\nOutput Shape: {output.shape}")

Random Tensor B: tensor([[0.6175, 0.5230, 0.1894, 0.0236, 0.4565, 0.4892, 0.1120]])

Multiplying: torch.Size([7, 7]) @ torch.Size([7, 1])

Output: tensor([[0.7580],
        [0.9529],
        [1.5018],
        [1.7175],
        [0.9409],
        [1.4215],
        [1.5940]])

Output Shape: torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [18]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_C = torch.rand(7, 7)
random_tensor_D = torch.rand(1, 7)

# Matrix multiply tensors
res = torch.matmul(random_tensor_C, random_tensor_D.T)
res, res.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [36]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [44]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device tensor is on: {device}")

# Create two random tensors on GPU
random_tensor_on_gpu_A = torch.rand(size=(2,3)).to(device)
random_tensor_on_gpu_B = torch.rand(size=(2,3)).to(device)

random_tensor_on_gpu_A, random_tensor_on_gpu_B

Device tensor is on: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [45]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(random_tensor_on_gpu_A, random_tensor_on_gpu_B.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find max
print(torch.min(result))

# Find min
print(torch.max(result))

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [48]:
# Find arg max
print(torch.argmax(result))

# Find arg min
print(torch.argmin(result))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [50]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand([1, 1, 1, 10])
print(rand_tensor, rand_tensor.shape)

# Remove single dimensions
rand_tensor_squeezed = rand_tensor.squeeze()
print(rand_tensor_squeezed, rand_tensor_squeezed.shape)

# Print out tensors and their shapes
print(f"Original Tensor Shape: {rand_tensor.shape}")
print(f"New Tensor Shape: {rand_tensor_squeezed.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
Original Tensor Shape: torch.Size([1, 1, 1, 10])
New Tensor Shape: torch.Size([10])
